
data_path: data/flowers
model_path: models/best_model.pt
model_name: vit_contrastive
container_name: vit_contrastive


# Train arguments
epochs: 5
batch_size: 32
learning_rate: 0.0005
# for data
n_negative: 3